/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DivisionsDivisionIdRouteImport } from './routes/divisions.$divisionId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DivisionsDivisionIdRoute = DivisionsDivisionIdRouteImport.update({
  id: '/divisions/$divisionId',
  path: '/divisions/$divisionId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/divisions/$divisionId': typeof DivisionsDivisionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/divisions/$divisionId': typeof DivisionsDivisionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/divisions/$divisionId': typeof DivisionsDivisionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/divisions/$divisionId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/divisions/$divisionId'
  id: '__root__' | '/' | '/divisions/$divisionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DivisionsDivisionIdRoute: typeof DivisionsDivisionIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/divisions/$divisionId': {
      id: '/divisions/$divisionId'
      path: '/divisions/$divisionId'
      fullPath: '/divisions/$divisionId'
      preLoaderRoute: typeof DivisionsDivisionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DivisionsDivisionIdRoute: DivisionsDivisionIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
